name = "eval"
version = "0.2.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
description = "A Gleam package to help you thread state through a series of steps."
repository = { type = "github", user = "hayleigh-dot-dev", repo = "gleam-eval" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
