name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          gleam-version: "1.0.0-rc2"
      # Stop trying to make gleam format happen, Louis, it's not going to happen.
      # - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
